version = 1

[envs.zsh]
channels = ["conda-forge"]
dependencies = { zsh = "*" }
exposed = { zsh = "zsh", "zsh-5.9" = "zsh-5.9" }

[envs.jupyterlab]
channels = ["conda-forge"]
dependencies = { jupyterlab = "*" , jupyter_console = "*", ipywidgets = "*", watchfiles = "*", jupyter_events = "*" , jupyter = "*" , jupytext = "*" , pynvim = "*", pillow = "*", cairosvg = "*" , euporie = "*" , timg = "*" }
exposed = { jupyter-lab = "jupyter-lab", jupyter-labextension = "jupyter-labextension", jupyter-labhub = "jupyter-labhub", jlpm = "jlpm", jupyter-console = "jupyter-console", watchfiles = "watchfiles", jupyter-events = "jupyter-events", jupyter = "jupyter", jupytext = "jupytext", jupytext-config = "jupytext-config", pynvim-python = "pynvim-python", cairosvg = "cairosvg", euporie = "euporie", euporie-console = "euporie-console", euporie-notebook = "euporie-notebook", euporie-preview = "euporie-preview", euporie-hub = "euporie-hub" }

[envs.dvc]
channels = ["conda-forge"]
dependencies = { dvc = "*" }
exposed = { dvc = "dvc" }

[envs.ncview]
channels = ["conda-forge"]
dependencies = { ncview = "*" }
exposed = { ncview = "ncview", ncdump = "ncdump" }


[envs.tree]
channels = ["conda-forge"]
dependencies = { tree = "*" }
exposed = { tree = "tree" }

[envs.nvim]
channels = ["conda-forge"]
dependencies = { nvim = "*" }
exposed = { nvim = "nvim" }

[envs.awscli]
channels = ["conda-forge"]
dependencies = { awscli = "*" }
exposed = { aws = "aws", aws_completer = "aws_completer" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.chezmoi]
channels = ["conda-forge"]
dependencies = { chezmoi = "*" }
exposed = { chezmoi = "chezmoi" }

[envs.fzf]
channels = ["conda-forge"]
dependencies = { fzf = "*" }
exposed = { fzf = "fzf" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }

[envs.glab]
channels = ["conda-forge"]
dependencies = { glab = "*" }
exposed = { glab = "glab" }

[envs.jq]
channels = ["conda-forge"]
dependencies = { jq = "*" }
exposed = { jq = "jq" }

[envs.lazydocker]
channels = ["conda-forge"]
dependencies = { lazydocker = "*" }
exposed = { lazydocker = "lazydocker" }

[envs.lazygit]
channels = ["conda-forge"]
dependencies = { lazygit = "*" }
exposed = { lazygit = "lazygit" }

[envs.nodejs]
channels = ["conda-forge"]
dependencies = { nodejs = "*" }
exposed = { node = "node", npm = "npm", npx = "npx" }

[envs.pipx]
channels = ["conda-forge"]
dependencies = { pipx = "*" }
exposed = { pipx = "pipx" }

[envs.rclone]
channels = ["conda-forge"]
dependencies = { rclone = "*" }
exposed = { rclone = "rclone" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }

[envs.yq]
channels = ["conda-forge"]
dependencies = { yq = "*" }
exposed = { tomlq = "tomlq", yq = "yq", xq = "xq" }

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.btop]
channels = ["conda-forge"]
dependencies = { btop = "*" }
exposed = { btop = "btop" }

[envs.anaconda-client]
channels = ["conda-forge"]
dependencies = { anaconda-client = "*" }
exposed = { anaconda = "anaconda" }

[envs.conda-build]
channels = ["conda-forge"]
dependencies = { conda-build = "*" }
exposed = { conda-build = "conda-build", conda-convert = "conda-convert", conda-debug = "conda-debug", conda-develop = "conda-develop", conda-inspect = "conda-inspect", conda-metapackage = "conda-metapackage", conda-render = "conda-render", conda-skeleton = "conda-skeleton" }

[envs.selenium]
channels = ["conda-forge"]
dependencies = { selenium = "*" }

[envs.firefox]
channels = ["conda-forge"]
dependencies = { firefox = "*" , gtk3 = "*" }
exposed = { firefox = "firefox", ".gtk3-post-link" = ".gtk3-post-link", gtk-builder-tool = "gtk-builder-tool", gtk-encode-symbolic-svg = "gtk-encode-symbolic-svg", gtk-launch = "gtk-launch", "gtk-query-immodules-3.0" = "gtk-query-immodules-3.0", gtk-query-settings = "gtk-query-settings", gtk-update-icon-cache = "gtk-update-icon-cache" }

[envs.geckodriver]
channels = ["conda-forge"]
dependencies = { geckodriver = "*" }
exposed = { geckodriver = "geckodriver" }

[envs.zip]
channels = ["conda-forge"]
dependencies = { zip = "*" }
exposed = { zip = "zip", zipcloak = "zipcloak", zipnote = "zipnote", zipsplit = "zipsplit" }

[envs.podman]
channels = ["conda-forge"]
dependencies = { podman = "*" }
exposed = { podman = "podman", podman-remote = "podman-remote", podmansh = "podmansh" }

[envs.miller]
channels = ["conda-forge"]
dependencies = { miller = "*" }
exposed = { mlr = "mlr" }

[envs.singularity]
channels = ["conda-forge"]
dependencies = { singularity = "*" }
exposed = { run-singularity = "run-singularity", singularity = "singularity" }

[envs.cookiecutter]
channels = ["conda-forge"]
dependencies = { cookiecutter = "*" }
exposed = { cookiecutter = "cookiecutter" }

[envs.yazi]
channels = ["conda-forge"]
dependencies = { yazi = "*", chafa = "*", python = "3.11.*", xarray = "*", zarr = "*", h5netcdf = "*" , dask = "*" , netcdf4 = "*" , pytorch-cpu = "*", lovely-tensors = "*" }
exposed = { yazi = "yazi", ya = "ya", chafa = "chafa"}

[envs.git]
channels = ["conda-forge"]
dependencies = { git = "*" }
exposed = { git = "git", git-cvsserver = "git-cvsserver", git-receive-pack = "git-receive-pack", git-shell = "git-shell", git-upload-archive = "git-upload-archive", git-upload-pack = "git-upload-pack", gitk = "gitk", scalar = "scalar" }

[envs.zoxide]
channels = ["conda-forge"]
dependencies = { zoxide = "*" }
exposed = { zoxide = "zoxide" }

[envs.eza]
channels = ["conda-forge"]
dependencies = { eza = "*" }
exposed = { eza = "eza" }

[envs.duckdb-cli]
channels = ["conda-forge"]
dependencies = { duckdb-cli = "*" }
exposed = { duckdb = "duckdb" }

[envs.nbpreview]
channels = ["conda-forge"]
dependencies = { nbpreview = "*" }
exposed = { nbp = "nbp", nbpreview = "nbpreview" }

